chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'


urlpatterns = [
    path('friends/', views.friends_list_to_chat, name='friends-list'),
    path('<str:username>/', views.ThreadView.as_view(), name="chat-room"),
]

connect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import user_login, user_signup, user_logout, notifications, profile_search_view, reset_password

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notifications/', notifications, name="notifications"),
    path('search/', profile_search_view, name="profile_search"),
    path('login/', user_login, name="login"),
    path('signup/', user_signup, name="signup"),
    path('reset_pwd/', reset_password, name="reset_pwd"),
    path('logout/', user_logout, name="logout"),
    path('profiles/', include('profiles.urls')),
    path('', include('posts.urls')),
    path('chat/', include('chat.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.home_view, name="home"),
    path('like/', views.post_like, name="like"),
    path('save/', views.post_save, name="save"),
    path('comment/', views.post_comment, name="comment"),
    path('delete/', views.post_delete, name="delete"),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('<str:slug>/', views.user_profile_detail_view,
         name="profile-detail-view"),
    path('edit/<str:slug>/', views.edit_profile_details, name="edit-profile"),
    path('follow/<str:slug>/', views.user_follow, name="user-follow"),
    path('unfollow/<str:slug>/', views.user_unfollow, name="user-unfollow"),
    path('confirm/<str:slug>/', views.confirm_follow_request, name="confirm-request"),
    path('delete/<str:slug>/', views.delete_follow_request, name="delete-request"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from profiles.models import Profile
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation

from connect.storage_backends import PublicMediaStorage

# Create your models here.


# class PostManager(models.Manager):
#     def get_all_users_who_liked(self, )


class Post(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    location = models.CharField(max_length=255, blank=True)
    text_content = models.TextField(blank=True)
    image = models.ImageField(blank=True, null=True, upload_to='posts/')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    comments = GenericRelation('Comment', related_query_name='post')
    likes = GenericRelation('Like', related_query_name='post')
    saved = GenericRelation('Saved', related_query_name='post')

    class Meta():
        ordering = ['-created']

    def __str__(self):
        return f"{self.pk}"

    def total_likes(self):
        return self.likes.all().count()

    def get_all_users_who_liked(self):
        users_likes = [like.user for like in self.likes.all()]
        return users_likes

    def get_all_users_who_saved(self):
        saved_posts = [save.user for save in self.saved.all()]
        return saved_posts

    def total_comments(self):
        return self.comments.all().count()


class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    text = models.CharField(max_length=255, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta():
        ordering = ['created']

    def __str__(self):
        return self.text


class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return f"{self.user}"


class Saved(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return f"{self.user}"

posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('location', 'text_content', 'image')


class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('text', )

posts/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core import serializers
from django.contrib.auth.models import User

from .models import *
from profiles.models import Profile, Relationship
from .forms import PostForm, CommentForm
# Create your views here.


@login_required
def home_view(request):
    admin_prof = Profile.objects.get(user__is_superuser=True)

    user = Profile.objects.get(user=request.user)

    friends = Relationship.objects.get_all_friends(user)
    friends = friends + [user]

    if admin_prof not in friends:
        friends.append(admin_prof)

    posts = Post.objects.filter(user__in=friends).order_by('-created')
    form = CommentForm()

    # pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 5)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context_data = {
        'posts': posts,
        'user': user,
        'form': form
    }
    return render(request, 'posts/posts.html', context_data)


@login_required
def post_like(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')
    user = Profile.objects.get(user=request.user)
    print(post_id + action)
    if post_id and action:
        print('inside if')
        try:
            post = Post.objects.get(pk=int(post_id))
            print(post)
            print('got the post')
            if action == 'like':
                post.likes.create(user=user)
                print('like created')
            else:
                post.likes.get(user=user).delete()
                print('like deleted')
            return JsonResponse({'status': 'ok', 'total_likes': post.likes.all().count()})
        except:
            print('did not got the post')
            pass
    return JsonResponse({'status': 'error'})


@login_required
def post_comment(request):
    profile = Profile.objects.get(user=request.user)
    if request.is_ajax and request.method == 'POST':
        post = Post.objects.get(id=request.POST.get('post_id'))
        comment = request.POST.get('text')
        new_comment = post.comments.create(user=profile, text=comment)
        new_comment.save()
        ser_instance = serializers.serialize(
            'json', [new_comment, profile, request.user])
        return JsonResponse({"instance": ser_instance}, status=200)
    return JsonResponse({"error": ""}, status=400)


@login_required
def post_delete(request):
    post_id = request.POST.get('id')
    try:
        post = Post.objects.get(pk=int(post_id))
        post.delete()
        return JsonResponse({'status': 'ok'})
    except:
        pass
    return JsonResponse({'error': 'error'})


@login_required
def post_save(request):
    user = Profile.objects.get(user=request.user)
    post_id = request.POST.get('id')
    action = request.POST.get('action')
    print(post_id, action)
    if post_id and action:
        print('inside if')
        try:
            post = Post.objects.get(pk=int(post_id))
            print(post)
            print('got the post')
            if action == 'save':
                post.saved.create(user=user)
                print('save created')
            else:
                post.saved.get(user=user).delete()
                print('save deleted')
            return JsonResponse({'status': 'ok'})
        except:
            print('did not got the post')
            pass
    return JsonResponse({'status': 'error'})

templates/posts/post_ajax.html
{% load static %}

{% for post in posts %}
    <div class="row post infinite-item" id="{{post.id}}">
        <div class="col m8 s12 offset-m2">
            <div class="card">
                <div class="user-info">
                    {% if post.user.avatar %}
                        <div class="user-info__avatar" style="background-image: url({{post.user.avatar.url}})">
                        </div>
                    {% else %}
                        <div class="user-info__avatar" style="background-image: url({% static 'images/user.png' %})">
                        </div>
                    {% endif %}
                    <div class="user-info__detail">
                        <a href="{% url 'profiles:profile-detail-view' post.user.slug %}" id="username"><p>{{post.user.user.username}}</p></a>
                        <p id="location">{{post.location}}</p>
                        <p id="time">{{post.created}}</p>
                    </div>
                    {% if section != 'save' %}
                        {% if curr_user_profile == user_profile %}
                        <a onclick="delete_func(this)" data-id="{{ post.id }}" class="delete tooltipped" data-position="bottom" data-tooltip="delete post"><i class="fas fa-trash"></i></a>
                        {% endif %}
                    {% endif %}
                </div>
                <div class="card-image">
                    {% if post.image %}
                        <img src="{{post.image.url}}" alt="" loading="lazy">
                    {% endif %}
                </div>
                <div class="card-content">
                    <p>{{post.text_content}}</p>
                </div>
                <div class="card-action" style="font-size:20px;display:flex;justify-content:space-around;border-bottom: 1px solid rgba(255,255,255,0.1);">
                    <a onclick="like_func(this)" data-id="{{ post.id }}" data-action="{% if user_profile in post.get_all_users_who_liked %}un{% endif %}like" class="like button tooltipped" style="color:red;cursor:pointer;" data-position="bottom" data-tooltip="like/unlike">
                        {% if user_profile not in post.get_all_users_who_liked %}
                            <i class="far fa-heart"></i>
                        {% else %}
                            <i class="fas fa-heart"></i>
                        {% endif %}
                        <span>{{post.likes.all.count}}</span>
                    </a>
                    <a onclick="save_func(this)" data-id="{{ post.id }}" data-action="{% if user_profile in post.get_all_users_who_saved %}un{% endif %}save" class="save button tooltipped" style="cursor:pointer;" data-position="bottom" data-tooltip="save/unsave">
                        {% if user_profile not in post.get_all_users_who_saved %}
                            <i class="far fa-bookmark"></i>
                        {% else %}
                            <i class="fas fa-bookmark"></i>
                        {% endif %}
                    </a>
                    <div class="share tooltipped" data-position="bottom" data-tooltip="share">
                        <a style="color:lightskyblue;cursor:pointer;"><i class="far fa-share"></i></a>
                    </div>
                </div>
                <div class="post-comments">
                    <ul class="collapsible">
                        <li>
                            <div class="collapsible-header heading">
                            <span id="total-com">{{post.comments.all.count}} Comment{{post.comments.all.count|pluralize}}</span>
                            </div>
                            <div class="collapsible-body" id="all_comments" style="border-top: 1px solid #ddd;">
                                {% for comment in post.comments.all %}
                                    <div class="comment">
                                        {% if comment.user.avatar %}
                                            <div class="comment-user" style="background-image:url({{comment.user.avatar.url}}); height: 30px;width: 30px;background-size: cover;border-radius: 50%;">
                                            </div>
                                        {% else %}
                                            <div class="comment-user" style="background-image:url({% static 'images/user.png' %}); height: 30px;width: 30px;background-size: cover;border-radius: 50%;">
                                            </div>
                                        {% endif %}
                                        <div class="comment-content">
                                            <div style="padding:10px;color:rgba(255,255,255, 0.85);">
                                                <p style="font-size:20px; color:#64ffda !important;">{{comment.user.user.username}}</p>
                                                <p>{{comment.text}}</p>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </li>
                    </ul>
                </div>
                <div id="comment-form-div">
                    <form onsubmit="comment_func(event)" class="comment-form" style="display:flex;flex-direction:row;align-items:center;" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{post.id}}>
                        <input type="text" name="text" maxlength="255" id="id_text" style="color: white;" placeholder="comment....">
                        <button class="btn waves-effect waves-light" type="submit" name="action"><span>Send</span>
                            <i class="material-icons right">send</i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

templates/posts/posts.html
{% extends 'base.html' %}
{% load static %}


{% block body_profile %}
    {% include 'messages.html' %}
    <div class="container infinite-container">
        {% include 'posts/post_ajax.html' %}
    </div>
    {% if posts.has_next %}
        <a class="infinite-more-link" href="?page={{ posts.next_page_number }}"></a>
    {% endif %}
    <div style="display:flex;flex-direction:row;justify-content:center">
        <div class="loading" style="display: none;">
            <div class="preloader-wrapper big active">
                <div class="spinner-layer spinner-blue-only">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="gap-patch">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body_profile %}