chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'


urlpatterns = [
    path('friends/', views.friends_list_to_chat, name='friends-list'),
    path('<str:username>/', views.ThreadView.as_view(), name="chat-room"),
]

connect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import user_login, user_signup, user_logout, notifications, profile_search_view, reset_password

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notifications/', notifications, name="notifications"),
    path('search/', profile_search_view, name="profile_search"),
    path('login/', user_login, name="login"),
    path('signup/', user_signup, name="signup"),
    path('reset_pwd/', reset_password, name="reset_pwd"),
    path('logout/', user_logout, name="logout"),
    path('profiles/', include('profiles.urls')),
    path('', include('posts.urls')),
    path('chat/', include('chat.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.home_view, name="home"),
    path('like/', views.post_like, name="like"),
    path('save/', views.post_save, name="save"),
    path('comment/', views.post_comment, name="comment"),
    path('delete/', views.post_delete, name="delete"),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('<str:slug>/', views.user_profile_detail_view,
         name="profile-detail-view"),
    path('edit/<str:slug>/', views.edit_profile_details, name="edit-profile"),
    path('follow/<str:slug>/', views.user_follow, name="user-follow"),
    path('unfollow/<str:slug>/', views.user_unfollow, name="user-unfollow"),
    path('confirm/<str:slug>/', views.confirm_follow_request, name="confirm-request"),
    path('delete/<str:slug>/', views.delete_follow_request, name="delete-request"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CONNECT</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block css %} {% block head_css_site %} {% endblock head_css_site %} {% endblock css %}
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@500&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</head>
<body>
    {% if request.user.is_authenticated %}
    <ul id="dropdown1" class="dropdown-content">
        <li><a href="{% url 'profiles:profile-detail-view' user_profile.slug %}"><i class="fas fa-user-circle"></i>  Profile</a></li>
        <li class="divider"></li>
        <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i>  Logout</a></li>
    </ul>
    <nav>
        <div class="nav-wrapper">
            <div>
                <a href="/" class="brand-logo">CONNECT</a>
                <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            </div>
            <ul class="right hide-on-med-and-down">
                <li class="tooltipped" data-position="bottom" data-tooltip="Home"><a href="{% url 'posts:home' %}"><i class="fas fa-home-alt"></i></a></li>
                <li class="tooltipped" data-position="bottom" data-tooltip="Search"><a href="{% url 'profile_search' %}"><i class="fas fa-search"></i></a></li>
                <li class="tooltipped" data-position="bottom" data-tooltip="Chat"><a href="{% url 'chat:friends-list' %}"><i class="fas fa-location-arrow"></i></a></li>
                <li class="tooltipped" data-position="bottom" data-tooltip="Notifications"><a href="{% url 'notifications' %}"><i class="fas fa-bell"></i><span style="background:red;border-radius:50%;">{% if total_noti %}{{total_noti}}{% endif %}</span></a></li>
                {% if user_profile.avatar %}
                    <li style="margin-top:17px;"><a class="dropdown-trigger" href="#!" data-target="dropdown1"><p class="avatar" style="background-image:url({{user_profile.avatar.url}}); height: 30px;width: 30px;background-size: cover;border-radius: 50%;"></p></a></li>
                {% else %}
                    <li><a class="dropdown-trigger" href="#!" data-target="dropdown1"><i class="fas fa-user-circle"></i></a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <ul class="sidenav" id="mobile-demo">
        <li><a href="{% url 'posts:home' %}"><i class="fas fa-home-alt" style="color:#26a69a"></i> Home</a></li>
        <li><a href="{% url 'profile_search' %}"><i class="fas fa-search" style="color:#26a69a"></i> Search</a></li>
        <li><a href="{% url 'chat:friends-list' %}"><i class="fas fa-location-arrow" style="color:#26a69a"></i> Chat</a></li>
        <li><a href="{% url 'notifications' %}"><i class="fas fa-bell" style="color:#26a69a"></i><span>{% if total_noti %}{{total_noti}}{% endif %}</span> Notifications</a></li>
        {% if user_profile.avatar %}
            <li style="margin-left:-8px;"><a href="{% url 'profiles:profile-detail-view' user_profile.slug %}" style="display:flex;align-items:center;"><p class="avatar_in_mob_view" style="background-image:url({{user_profile.avatar.url}}); height: 30px !important;width: 30px !important;background-size: cover;border-radius: 50%;"></p> <span style="padding-left:34px;">Profile</span></a></li>
        {% else %}
            <li style="margin-left:-4px;"><a href="{% url 'profiles:profile-detail-view' user_profile.slug %}" style="display:flex;align-items:center;"><i class="fas fa-user-circle" style="font-size:20px;color:#26a69a;"></i> <span style="padding-left:8px;">Profile</span></a></li>
        {% endif %}
        <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt" style="color:#26a69a"></i>  Logout</a></li>
    </ul>
    {% endif %}

    {% block body_profile %}
    {% endblock body_profile %}

    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/infinite.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
        var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
                $('.loading').show();
            },
            onAfterPageLoad: function ($items) {
                $('.loading').hide();
                $('.collapsible').collapsible();
                $('.tooltipped').tooltip();
            }
        });

        $(".dropdown-trigger").dropdown();

        $(document).ready(function(){
            $('.tabs').tabs();
            $('.sidenav').sidenav();
        });

        $(document).ready(function(){
            $('.modal').modal();
        });

        $('input').css('color', 'white')
        $('textarea').css('color', 'white')
        M.textareaAutoResize($('textarea'));

        document.addEventListener('DOMContentLoaded', function() {
            $('.collapsible').collapsible();
        });

        $(document).ready(function(){
            $('.tooltipped').tooltip();
        });

        var csrftoken = Cookies.get('csrftoken');
        function csrfSafeMethod(method) {
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
            }
        });

        {% block domready %}
        {% endblock %}

        function like_func(el){
            //e.preventDefault();
            var previous_action = el.getAttribute('data-action');
            var like_button = el;
            console.log(previous_action);
            console.log(like_button);
            $.ajax({
                type: 'POST',
                url: '{% url "posts:like" %}',
                data: {
                    id: el.getAttribute('data-id'),
                    action: el.getAttribute('data-action'),
                },
                success: function(data){
                    if (data['status'] == 'ok')
                    {
                        console.log(data);
                        // toggle data-action
                        like_button.setAttribute('data-action', previous_action == 'like' ?
                        'unlike' : 'like');
                        // toggle link text
                        if(like_button.getAttribute('data-action') == 'like') {
                            like_button.innerHTML = `<i class="far fa-heart"></i><span> ${data.total_likes}</span>`;
                        } else {
                            like_button.innerHTML = `<i class="fas fa-heart"></i><span> ${data.total_likes}</span>`;
                        }
                    }
                },
                error: function (response) {
                    console.log('error')
                }
            });
        };

        function comment_func (e){
            e.preventDefault();
            var target = e.target;
            console.log(target.childNodes);
            var post_id = target.childNodes[3].value;
            var text = target.childNodes[5].value;
            var serializedData = {
                'post_id': post_id,
                'text': text
            };
            console.log(serializedData);
            var comment_list = target.parentNode.previousSibling.previousSibling.childNodes[1].childNodes[1].childNodes[3];
            console.log(comment_list);
            var total_comments_el = target.parentNode.previousSibling.previousSibling.childNodes[1].childNodes[1].childNodes[1].childNodes[1];
            console.log(total_comments_el);
            var total_comments = total_comments_el.textContent;
            var total = parseInt(total_comments) + 1;
            $.ajax({
                type: 'POST',
                url: "{% url 'posts:comment' %}",
                data: serializedData,
                success: function (response) {
                    target.reset();

                    var instance = JSON.parse(response["instance"]);
                    var text = instance[0]["fields"]["text"];
                    var avatar_url = instance[1]["fields"]["avatar"];
                    var username = instance[2]["fields"]["username"];
                    console.log(text);
                    console.log(avatar_url);
                    console.log(username);

                    var com_div = document.createElement('div');
                    com_div.setAttribute('class', 'comment');

                    var com_user_div = document.createElement('div');
                    com_user_div.setAttribute('class', 'comment-user');
                    com_user_div.setAttribute('style', `background-image:url(${avatar_url?"https://manav-connect-bucket.s3.amazonaws.com/media/"+avatar_url:"{% static 'images/user.png' %}"}); height: 30px;width: 30px;background-size: cover;border-radius: 50%;`);

                    com_div.append(com_user_div);

                    var com_cont_div = document.createElement('div');
                    com_cont_div.setAttribute('class', 'comment-content');

                    var div = document.createElement('div');
                    div.setAttribute('style', 'padding:10px;color:rgba(255,255,255, 0.85);');

                    var user_p = document.createElement('p');
                    user_p.setAttribute('style', 'font-size:18px; color:#64ffda !important;');
                    user_p.textContent = username;

                    var text_p = document.createElement('p');
                    text_p.textContent = text;

                    div.append(user_p);
                    div.append(text_p);
                    com_cont_div.append(div);

                    com_div.append(com_cont_div);

                    comment_list.append(com_div);

                    if (total > 1) {
                        total_comments_el.textContent = total + ' Comments';
                    } else {
                        total_comments_el.textContent = total + ' Comment';
                    }
                },
                error: function (response) {
                    console.log('error')
                }
            })
        }

        function save_func(el){
            var previous_action = el.getAttribute('data-action');
            var post_id = el.getAttribute('data-id');
            var save_button = el;
            console.log(previous_action);
            console.log(save_button);
            console.log(post_id);
            $.ajax({
                type: 'POST',
                url: '{% url "posts:save" %}',
                data: {
                    id: el.getAttribute('data-id'),
                    action: el.getAttribute('data-action'),
                },
                success: function(data){
                    if (data['status'] == 'ok')
                    {
                        console.log(data);
                        // toggle data-action
                        save_button.setAttribute('data-action', previous_action == 'save' ?
                        'unsave' : 'save');
                        // toggle link text
                        if(save_button.getAttribute('data-action') == 'save') {
                            save_button.innerHTML = `<i class="far fa-bookmark"></i>`;
                        } else {
                            save_button.innerHTML = `<i class="fas fa-bookmark"></i>`;
                        }
                    }
                },
                error: function (response) {
                    console.log('error')
                }
            });
        };
    </script>
</body>
</html>

templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" style="margin: auto;margin-top: 10px;width: 90%; background: cadetblue;padding: 10px;border-radius: 10px;color: whitesmoke;">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="float: right;background: transparent;border: none;cursor:pointer;">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
{% endif %}

<script>
    document.querySelector('.close').addEventListener('click', function(e) {
        var target = e.target;
        target.parentNode.parentNode.remove();
    });
</script>

templates/notifications.html
{% extends 'base.html' %}
{% load static %}
{% block head_css_site %}
    <link rel="stylesheet" href="{% static 'css/notifications.css' %}">
{% endblock head_css_site %}

{% block body_profile %}
    <div class="container">
        <div class="row" style="border-bottom: 1px solid rgba(255, 255, 255, 0.2);">
            <h4 style="color:white">Notifications</h4>
        </div>
        <div class="row noti">
            {% for follow_request in follow_requests %}
                <div class="noti__detail">
                    <div style="display:flex; flex-direction: row; align-items:center">
                        {% if follow_request.sender.avatar %}
                            <div class="noti__avatar" style="background-image:url({{follow_request.sender.avatar.url}})"></div>
                        {% else %}
                            <div class="noti__avatar" style="background-image:url({% static 'images/user.png' %})"></div>
                        {% endif %}
                        <p style="margin-left:20px" class="noti__text"><span style="color:#26a69a;font-size:20px;">{{follow_request.sender.user.username}}</span> sent you friend request </p>
                    </div>
                    <div style="display:flex; flex-direction: row; align-items:center" class="buttons">
                        <a href="{% url 'profiles:confirm-request' follow_request.sender.slug %}" class="btn"><i class="fas fa-check"></i></a>
                        <a href="{% url 'profiles:delete-request' follow_request.sender.slug %}" class="btn" style="margin-left:20px;"><i class="fas fa-trash"></i></a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock body_profile %}

{% comment %} {% block domready %}
    $('.delete').click(function(e) {
        e.preventDefault();
        console.log($(this).parent().parent()[0]);
        var req_div = $(this).parent().parent()[0];
        console.log($(this).data('slug'));
        $.ajax({
            type: 'POST',
            url: "{% url 'profiles:delete-request' %}",
            data: {
                slug: $(this).data('slug')
            },
            success: function(data) {
                req_div.remove();
            },
            error: function(error) {
                console.log(error);
            }
        });
    })
{% endblock domready %} {% endcomment %}

templates/search.html
{% extends 'base.html' %}

{% load static %}
{% block head_css_site %}
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
{% endblock head_css_site %}

{% block body_profile %}

{% if query %} 
    <div class="container">
        <div class="row" style="color: rgba(255,255,255, 0.75)">
            <h2> Profile containing <span style="color: #26a69a">"{{ query }}"</span> </h1> 
            <h4> {% with results.count as total_results %} Found {{ total_results }} result{{ total_results | pluralize }} {% endwith %} </h3> 
        </div>
        <ul class="collection">
        {% for profile in results %}
            <li class="collection-item avatar">
                {% if profile.avatar %}
                    <img src="{{ profile.avatar.url }}" alt="" class="circle">
                {% else %}
                    <img src="{% static 'images/user.png' %}" alt="" class="circle">
                {% endif %}
                <a href="{% url 'profiles:profile-detail-view' profile.slug %}" class="title" style="color: #26a69a;font-size:20px;">{{profile.user.username}}</a> 
                <p style="color: grey">
                    {{profile.first_name}} {{profile.last_name}}
                </p>
                <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
            </li>
        {% endfor %}
        <p><a href ="{% url "profile_search" %}" class="btn"> Search again </a> </p> 
        </ul>
    </div>
{% else %}
    <div class="container">
        <div class="row" style="color: rgba(255,255,255, 0.75)">
            <h1> Search for Profiles </h1> 
        </div>
        <div class="row">
            <form method="get">
                {{ form.as_p }} 
                <button class="waves-effect waves-light btn" type="submit">Search</button>
            </form>
        </div>
        <ul class="collection">
        {% for profile in profiles %}
            <li class="collection-item avatar">
                {% if profile.avatar %}
                    <img src="{{ profile.avatar.url }}" alt="" class="circle">
                {% else %}
                    <img src="{% static 'images/user.png' %}" alt="" class="circle">
                {% endif %}
                <a href="{% url 'profiles:profile-detail-view' profile.slug %}" class="title" style="color: #26a69a;font-size:20px;">{{profile.user.username}}</a> 
                <p style="color: grey">
                    {{profile.first_name}} {{profile.last_name}}
                </p>
                <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
            </li>
        {% endfor %}
        </ul>
    </div>
{% endif %}



{% endblock body_profile %}