chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'


urlpatterns = [
    path('friends/', views.friends_list_to_chat, name='friends-list'),
    path('<str:username>/', views.ThreadView.as_view(), name="chat-room"),
]

connect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import user_login, user_signup, user_logout, notifications, profile_search_view, reset_password

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notifications/', notifications, name="notifications"),
    path('search/', profile_search_view, name="profile_search"),
    path('login/', user_login, name="login"),
    path('signup/', user_signup, name="signup"),
    path('reset_pwd/', reset_password, name="reset_pwd"),
    path('logout/', user_logout, name="logout"),
    path('profiles/', include('profiles.urls')),
    path('', include('posts.urls')),
    path('chat/', include('chat.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.home_view, name="home"),
    path('like/', views.post_like, name="like"),
    path('save/', views.post_save, name="save"),
    path('comment/', views.post_comment, name="comment"),
    path('delete/', views.post_delete, name="delete"),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('<str:slug>/', views.user_profile_detail_view,
         name="profile-detail-view"),
    path('edit/<str:slug>/', views.edit_profile_details, name="edit-profile"),
    path('follow/<str:slug>/', views.user_follow, name="user-follow"),
    path('unfollow/<str:slug>/', views.user_unfollow, name="user-unfollow"),
    path('confirm/<str:slug>/', views.confirm_follow_request, name="confirm-request"),
    path('delete/<str:slug>/', views.delete_follow_request, name="delete-request"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from profiles.models import Profile
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation

from connect.storage_backends import PublicMediaStorage

# Create your models here.


# class PostManager(models.Manager):
#     def get_all_users_who_liked(self, )


class Post(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    location = models.CharField(max_length=255, blank=True)
    text_content = models.TextField(blank=True)
    image = models.ImageField(blank=True, null=True, upload_to='posts/')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    comments = GenericRelation('Comment', related_query_name='post')
    likes = GenericRelation('Like', related_query_name='post')
    saved = GenericRelation('Saved', related_query_name='post')

    class Meta():
        ordering = ['-created']

    def __str__(self):
        return f"{self.pk}"

    def total_likes(self):
        return self.likes.all().count()

    def get_all_users_who_liked(self):
        users_likes = [like.user for like in self.likes.all()]
        return users_likes

    def get_all_users_who_saved(self):
        saved_posts = [save.user for save in self.saved.all()]
        return saved_posts

    def total_comments(self):
        return self.comments.all().count()


class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    text = models.CharField(max_length=255, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta():
        ordering = ['created']

    def __str__(self):
        return self.text


class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return f"{self.user}"


class Saved(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return f"{self.user}"

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.db.models import Q


from connect.storage_backends import PublicMediaStorage


# Create your models here.

GENDER = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Others', 'Others'),
    ('Perfer Not To Say', 'Perfer Not To Say')
)


class ProfileManager(models.Manager):
    def get_all_profiles(self, me):
        return Profile.objects.all().exclude(user=me)

    def get_saved_posts(self, me, post_class):
        saved_posts_ids = [post.object_id for post in me.saved_set.all()]
        saved_posts = post_class.objects.filter(id__in=saved_posts_ids)
        return saved_posts


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=True)
    bio = models.TextField(blank=True)
    gender = models.CharField(choices=GENDER, blank=True, max_length=25)
    country = models.CharField(max_length=255, blank=True)
    avatar = models.ImageField(
        upload_to='avatars/', null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username}"

    @property
    def get_username(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse("profiles:profile-detail-view", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        slug_text = f"{self.user.username}"
        self.slug = slugify(slug_text)
        return super(Profile, self).save(*args, **kwargs)


STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)


class RelationshipManager(models.Manager):
    def get_all_request_by_me(self, me):
        return Relationship.objects.filter(sender=me, status='send').only('receiver')

    def get_all_followers(self, receiver):
        return Relationship.objects.filter(receiver=receiver, status='accepted').only('sender')

    def get_all_following(self, sender):
        return Relationship.objects.filter(sender=sender, status='accepted').only('receiver')

    def get_all_friends(self, me):
        all_friends = Relationship.objects.filter(
            (Q(sender=me) | Q(receiver=me)) & Q(status='accepted')).only('sender', 'receiver')
        friends_profiles = []
        for friend in all_friends:
            if friend.sender == me:
                friends_profiles.append(friend.receiver)
            else:
                friends_profiles.append(friend.sender)
        return list(set(friends_profiles))


class Relationship(models.Model):
    sender = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender.user.username} - {self.receiver.user.username} - {self.status} - {self.created}"

profiles/forms.py
from django import forms
from django.forms.widgets import Select

from .models import Profile
from posts.models import Post
from django.contrib.auth.models import User

GENDER = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Others', 'Others'),
    ('Perfer Not To Say', 'Perfer Not To Say'),
)


class ProfileUpdateForm(forms.ModelForm):
    avatar = forms.ImageField(required=False)
    gender = forms.ChoiceField(choices=GENDER)

    class Meta():
        model = Profile
        fields = ('first_name', 'last_name', 'bio',
                  'gender', 'country', 'avatar')

profiles/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponseForbidden, JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages

from profiles.models import Profile, Relationship
from posts.models import Post, Comment, Like, Saved
from .forms import ProfileUpdateForm
from posts.forms import PostForm, CommentForm
from connect.storage_backends import PublicMediaStorage

import os

# Create your views here.


@login_required
def user_profile_detail_view(request, slug):
    curr_user_profile = Profile.objects.get(slug=slug)
    auth_user_profile = Profile.objects.get(user=request.user)

    auth_user_following = Relationship.objects.get_all_following(
        auth_user_profile)
    auth_user_follower = Relationship.objects.get_all_followers(
        auth_user_profile)

    auth_user_following_profiles = [
        following.receiver for following in auth_user_following]
    auth_user_follower_profiles = [
        follower.sender for follower in auth_user_follower]

    followings = Relationship.objects.get_all_following(
        curr_user_profile)
    followers = Relationship.objects.get_all_followers(
        curr_user_profile)

    following_profiles = [following.receiver for following in followings]
    follower_profiles = [follower.sender for follower in followers]

    requests_by_me = Relationship.objects.get_all_request_by_me(
        me=auth_user_profile)
    my_request_profiles = [i.receiver for i in requests_by_me]

    posts = curr_user_profile.post_set.all()
    saved_posts = Profile.objects.get_saved_posts(auth_user_profile, Post)

    # form = CommentForm()

    # pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 5)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    page = request.GET.get('page', 1)
    paginator = Paginator(saved_posts, 5)
    try:
        saved_posts = paginator.page(page)
    except PageNotAnInteger:
        saved_posts = paginator.page(1)
    except EmptyPage:
        saved_posts = paginator.page(paginator.num_pages)

    context_data = {
        'curr_user_profile': curr_user_profile,
        'followings': followings,
        'followers': followers,
        'following_profiles': following_profiles,
        'follower_profiles': follower_profiles,
        'auth_user_profile': auth_user_profile,
        'auth_user_following': auth_user_following,
        'auth_user_follower': auth_user_follower,
        'auth_user_following_profiles': auth_user_following_profiles,
        'auth_user_follower_profiles': auth_user_follower_profiles,
        'my_request_profiles': my_request_profiles,
        'posts': posts,
        'saved_posts': saved_posts,
    }

    # form for creating posts
    if auth_user_profile == curr_user_profile:
        if request.method == 'POST':
            form = PostForm(request.POST, request.FILES)
            if form.is_valid():
                new_post = form.save(commit=False)
                new_post.user = auth_user_profile
                new_post.save()
                return HttpResponseRedirect(reverse('profiles:profile-detail-view', kwargs={'slug': auth_user_profile.slug}))
        else:
            form = PostForm()
        context_data['form'] = form

    return render(request, 'profiles/profile-detail.html', context_data)


@login_required
def edit_profile_details(request, slug):
    profile = get_object_or_404(Profile, slug=slug)
    if (profile.user == request.user):
        if request.method == 'POST':
            form = ProfileUpdateForm(request.POST or None,
                                     request.FILES or None,
                                     instance=profile)
            if form.is_valid:
                form.save()
                messages.success(request, 'PROFILE WAS UPDATED SUCCESSFULLY')
                return HttpResponseRedirect(reverse('profiles:profile-detail-view', kwargs={'slug': slug}))
        else:
            form = ProfileUpdateForm(instance=profile)
            return render(request, 'profiles/edit.html', {
                'form': form
            })
    else:
        return HttpResponseForbidden()


@login_required
def user_follow(request, slug):
    receiver = Profile.objects.get(slug=slug)
    sender = Profile.objects.get(user=request.user)
    Relationship.objects.get_or_create(
        receiver=receiver, sender=sender, status='send')
    # display message
    return HttpResponseRedirect(reverse('profiles:profile-detail-view', kwargs={'slug': slug}))


@login_required
def user_unfollow(request, slug):
    me = Profile.objects.get(user=request.user)
    other_user = Profile.objects.get(slug=slug)
    Relationship.objects.filter(
        receiver=other_user, sender=me, status='accepted').delete()
    return HttpResponseRedirect(reverse('profiles:profile-detail-view', kwargs={'slug': me.slug}))


@login_required
def confirm_follow_request(request, slug):
    me = Profile.objects.get(user=request.user)
    other_user = Profile.objects.get(slug=slug)
    Relationship.objects.filter(
        receiver=me, sender=other_user, status='send').update(status='accepted')
    return HttpResponseRedirect(reverse('notifications'))


@login_required
def delete_follow_request(request, slug):
    me = Profile.objects.get(user=request.user)
    other_user = Profile.objects.get(slug=slug)
    Relationship.objects.filter(
        receiver=me, sender=other_user, status='send').delete()
    return HttpResponseRedirect(reverse('notifications'))

templates/profiles/edit.html
{% extends 'base.html' %}

{% load static %}
{% block head_css_site %}
    <link rel="stylesheet" href="{% static 'css/profiles/edit.css' %}">
{% endblock head_css_site %}

{% block body_profile %}

<div class="row">
    <div class="edit-form col m6 s10 offset-s1 offset-m3" style="color:white;">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button style="margin-top: 10px;" class="btn" type="submit">Update</button>
        </form>
    </div>
</div>

{% endblock body_profile %}

templates/profiles/profile-detail.html
{% extends 'base.html' %}
{% load static %}
{% block head_css_site %}
    <link rel="stylesheet" href="{% static 'css/profiles/profile-detail.css' %}">
{% endblock head_css_site %}

{% block body_profile %}
{% include 'messages.html' %}
<div class="container">
    <div class="profile__overview row">
        <div class="col s4">
            {% if curr_user_profile.avatar %}
                <a href="{{curr_user_profile.avatar.url}}">
                    <div class="avatar" style="background-image: url({{curr_user_profile.avatar.url}})">
                    </div>
                </a>
            {% else %}
                <div class="avatar" style="background-image: url({% static 'images/user.png' %})">
                </div>
            {% endif %}
        </div>
        <div class="col s8">
            <div class="overview">
                <div class="row__1">
                    <h4>{{ curr_user_profile.user.username }}</h4>
                    {% if auth_user_profile == curr_user_profile %}
                        <a href="{% url 'profiles:edit-profile' auth_user_profile.slug %}" class="btn waves-effect waves-light" type="submit" name="action">Edit Profile <i class="fas fa-cog"></i></a>
                    {% elif auth_user_profile in follower_profiles and auth_user_profile not in following_profiles %}
                        <a href="{% url 'chat:chat-room' curr_user_profile.user.username %}" class="btn waves-effect waves-light" type="submit" name="action">Message</a>
                        <a href="{% url 'profiles:user-unfollow' curr_user_profile.slug %}" class="btn waves-effect waves-light" type="submit" name="action">Unfollow</a>
                    {% elif curr_user_profile in my_request_profiles %}
                        <a class="btn waves-effect waves-light" type="submit" name="action">Requested <i class="fas fa-check"></i></a>
                    {% elif auth_user_profile not in following_profiles %}
                        <a href="{% url 'profiles:user-follow' curr_user_profile.slug %}" class="btn waves-effect waves-light" type="submit" name="action">Follow</a>
                    {% elif auth_user_profile in follower_profiles and curr_user_profile in auth_user_follower_profiles %}
                        <a href="{% url 'chat:chat-room' curr_user_profile.user.username %}" class="btn waves-effect waves-light" type="submit" name="action">Message</a>
                        <a href="{% url 'profiles:user-unfollow' curr_user_profile.slug %}" class="btn waves-effect waves-light" type="submit" name="action">Unfollow</a>
                    {% elif auth_user_profile not in follower_profiles and curr_user_profile in auth_user_follower_profiles %}
                        <a href="{% url 'profiles:user-follow' curr_user_profile.slug %}" class="btn waves-effect waves-light" type="submit" name="action">Follow Back</a>
                    {% endif %}
                </div>
                <div class="row__2">
                    <p>{{curr_user_profile.post_set.all.count}} post{{curr_user_profile.post_set.all.count|pluralize}}</p>
                    <a class="modal-trigger" data-target="modal1">{{ followers.count }} follower{{ followers.count|pluralize}}</a>
                    <a class="modal-trigger" data-target="modal2">{{ followings.count }} following{{ followings.count|pluralize }}</a>
                </div>
                <div class="row__3">
                    <p class="fullname" style="font-size:20px;font-weight:500px;">{{curr_user_profile.first_name}} {{curr_user_profile.last_name}}</p>
                    <p class="bio" style="font-size:19px;font-weight:500px;">{{ curr_user_profile.bio }}</p>
                </div>
            </div>
        </div>
    </div>
    <!--START OF FOLLOWERS MODEL-->
        <div id="modal1" class="modal modal-fixed-footer">
            <div class="modal-content">
                <div class="fol__header">
                    <h4>Followers</h4>
                </div>
                <div>
                    {% for follower in followers %}
                        <div class="fol__detail">
                            <a href="{% url 'profiles:profile-detail-view' follower.sender.slug %}">
                                <div style="display: flex; align-items: center;">
                                    {% if follower.sender.avatar %}
                                        <p class="fol__avatars" style="background-image:url({{follower.sender.avatar.url}})"></p>
                                    {% else %}
                                        <p class="fol__avatars" style="background-image:url({% static 'images/user.png' %})"></p>
                                    {% endif %}
                                    <p class="fol_username">{{follower.sender.user.username}}</p>
                                </div>
                            </a>
                            <div>
                                {% if auth_user_profile != follower.sender %}
                                    {% if follower.sender in auth_user_following_profiles %}
                                        <button class="btn fol_buttons">Following</button>
                                    {% elif follower.sender in my_request_profiles %}
                                        <button class="btn fol_buttons">Requested <i class="fas fa-check"></i></button>
                                    {% else %}
                                        <a href="{% url 'profiles:user-follow' follower.sender.slug %}" class="btn fol_buttons" style="color:white;">Follow</a>
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="modal-footer">
                <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
            </div>
        </div>
    <!--END OF FOLLOWERS MODEL-->
    <!--START OF FOLLOWING MODEL-->
        <div id="modal2" class="modal modal-fixed-footer">
            <div class="modal-content">
                <div class="fol__header">
                    <h4>Following</h4>
                </div>
                <div>
                    {% for following in followings %}
                        <div class="fol__detail">
                            <a href="{% url 'profiles:profile-detail-view' following.receiver.slug %}">
                                <div style="display: flex; align-items: center;">
                                    {% if following.receiver.avatar %}
                                        <p class="fol__avatars" style="background-image:url({{following.receiver.avatar.url}})"></p>
                                    {% else %}
                                        <p class="fol__avatars" style="background-image:url({% static 'images/user.png' %})"></p>
                                    {% endif %}
                                    <p class="fol_username">{{following.receiver.user.username}}</p>
                                </div>
                            </a>
                            <div>
                                {% if auth_user_profile != following.receiver %}
                                    {% if following.receiver in auth_user_following_profiles %}
                                        <button class="btn fol_buttons">Following</button>
                                    {% elif following.receiver in my_request_profiles %}
                                        <button class="btn fol_buttons">Requested <i class="fas fa-check"></i></button>
                                    {% else %}
                                        <a href="{% url 'profiles:user-follow' following.receiver.slug %}" class="btn fol_buttons" style="color:white;">Follow</a>
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="modal-footer">
                <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
            </div>
        </div>
    <!--END OF FOLLOWING MODEL-->
    {% if form %}
        <div class="row">
            <div class="create" style="display:flex;flex-direction:row;justify-content:center;">
                <form method="post" class="z-depth-2" style="display:flex;flex-direction:column;background-color: #242526;padding:25px;border-radius:max(0px, min(8px, calc((100vw - 4px - 100%) * 9999))) / 8px;color:white !important;" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button style="margin-top:10px" type="submit" class="btn">POST</button>
                </form>
            </div>
        </div>
    {% endif %}
    <div>
        <div class="divider"></div>
        <ul id="tabs-swipe-demo" class="tabs">
            <li class="tab col s3"><a class="active" href="#test-swipe-1">POSTS</a></li>
            {% if curr_user_profile == user_profile %}
                <li class="tab col s3"><a href="#test-swipe-2">SAVED</a></li>
            {% endif %}
        </ul>
        <div class="divider"></div>
        <div id="test-swipe-1" class="col s12">
            <div class="container infinite-container">
                {% include 'posts/post_ajax.html' %}
            </div>
            {% if posts.has_next %}
                <a class="infinite-more-link" href="?page={{ posts.next_page_number }}"></a>
            {% endif %}
            <div style="display:flex;flex-direction:row;justify-content:center">
                <div class="loading" style="display: none;">
                    <div class="preloader-wrapper big active">
                        <div class="spinner-layer spinner-blue-only">
                            <div class="circle-clipper left">
                                <div class="circle"></div>
                            </div>
                            <div class="gap-patch">
                                <div class="circle"></div>
                            </div>
                            <div class="circle-clipper right">
                                <div class="circle"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if curr_user_profile == user_profile %}
        <div id="test-swipe-2" class="col s12">
        {% with saved_posts as posts %}
            <div class="container infinite-container">
                {% with section='save'  %}
                    {% include 'posts/post_ajax.html' %}
                {% endwith %}
            </div>
            {% if posts.has_next %}
                <a class="infinite-more-link" href="?page={{ posts.next_page_number }}"></a>
            {% endif %}
            <div style="display:flex;flex-direction:row;justify-content:center">
                <div class="loading" style="display: none;">
                    <div class="preloader-wrapper big active">
                        <div class="spinner-layer spinner-blue-only">
                            <div class="circle-clipper left">
                                <div class="circle"></div>
                            </div>
                            <div class="gap-patch">
                                <div class="circle"></div>
                            </div>
                            <div class="circle-clipper right">
                                <div class="circle"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endwith %}
        </div>
        {% endif %}
    </div>
</div>

{% endblock body_profile %}

{% block domready %}
    function delete_func(el) {
        console.log(el.parentNode.parentNode.parentNode.parentNode);
        var id = el.getAttribute('data-id');
        console.log(id);
        var post_node = el.parentNode.parentNode.parentNode.parentNode;
        $.ajax({
            type: 'POST',
            url: "{% url 'posts:delete' %}",
            data:
            {
                id: id
            },
            success: function(data) {
                post_node.remove();
            },
            error: function(error) {
                console.log(error);
            }
        });
    };
{% endblock domready %}